MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Models/Siniflar/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class Personel
    {
        [Key]
        public int PersonelID { get; set; }

        [Display(Name = "Personel Adı")]
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelAd { get; set; }

        [Display(Name = "Personel Soyadı")]
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelSoyad { get; set; }

        [Display(Name = "Görsel")]
        [Column(TypeName = "Varchar")]
        [StringLength(300)]
        public string PersonelGorsel { get; set; }
        public ICollection<SatisHareket> SatisHarekets { get; set; }
        public int DepartmanID { get; set; }
        public virtual Departman Departman { get; set; }
    }
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Controllers/PersonelController.cs
using MvcOnlineTicariOtomasyon.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class PersonelController : Controller
    {
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Personels.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult PersonelEkle()
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.DepartmanID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            return View();
        }
        [HttpPost]
        public ActionResult PersonelEkle(Personel p)
        {
          if(Request.Files.Count > 0)
            {
                string dosyadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/Image/" + dosyadi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                p.PersonelGorsel = "/Image/" + dosyadi + uzanti;
            }
            c.Personels.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.DepartmanID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            var prs = c.Personels.Find(id);
            return View("PersonelGetir", prs); ;
        }
        public ActionResult PersonelGuncelle(Personel p)
        {

            if (Request.Files.Count > 0)
            {
                string dosyadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/Image/" + dosyadi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                p.PersonelGorsel = "/Image/" + dosyadi + uzanti;
            }
            var prsn = c.Personels.Find(p.PersonelID);
            prsn.PersonelAd = p.PersonelAd;
            prsn.PersonelSoyad = p.PersonelSoyad;
            prsn.PersonelGorsel = p.PersonelGorsel;
            prsn.DepartmanID = p.DepartmanID;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelListe()
        {
            var sorgu = c.Personels.ToList();
            return View(sorgu);
        }

    }
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Personel/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>ID</th>
        <th>Personel Adı</th>
        <th>Soyad</th>
        <th>Görsel</th>
        <th>Departman</th>
        <th>Güncelle</th>
        <th>Satışlar</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.PersonelID</td>
            <td>@k.PersonelAd</td>
            <td>@k.PersonelSoyad</td>
            <td><img src="@k.PersonelGorsel" style="width:100px; height:100px" alt="Alternate Text" /></td>
            <td>@k.Departman.DepartmanAd</td>
            <td><a href="/Personel/PersonelGetir/@k.PersonelID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Departman/DepartmanPersonelSatis/@k.PersonelID" class="btn btn-default" style="background-color:lightcoral; color:white">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Personel/PersonelEkle" class="btn btn-info">Personel Ekle</a>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Personel/PersonelEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Personel
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Personel Sayfası</h2>
<br />
@using (Html.BeginForm("PersonelEkle", "Personel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <form class="form-group" method="post">
        @Html.LabelFor(x => x.PersonelAd)
        @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelSoyad)
        @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelGorsel)
        @*@Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })*@
        <input type="file" name="PersonelGorsel" />
        <br />
        @Html.LabelFor(x => x.Departman)
        @Html.DropDownListFor(x => x.DepartmanID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        @*@Html.TextBoxFor(x => x.Kategoriid, new { @class = "form-control" })*@
        <br />
        <button class="btn btn-primary">Kaydet</button>
    </form>
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Personel/PersonelGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Personel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Cari Güncelleme Ekranı</h2>
<br />
@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.PersonelID)
        @Html.LabelFor(x => x.PersonelAd)
        @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelSoyad)
        @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelGorsel)
        <input type="file" name="PersonelGorsel" />
        <br />
        @Html.LabelFor(x => x.Departman)
        @Html.DropDownListFor(x => x.DepartmanID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        <br />
        <button class="btn btn-default" style="background-color:yellowgreen">Güncelle</button>
    </div>
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Personel/PersonelListe.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "PersonelListe";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Contacts</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Personeller</h1>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <!-- Default box -->
            <div class="card card-solid">
                <div class="card-body pb-0">
                    <div class="row d-flex align-items-stretch">
                        @foreach (var x in Model)
                        {
                            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                                <div class="card bg-light">
                                    <div class="card-header text-muted border-bottom-0">
                                        @x.Departman.DepartmanAd
                                    </div>
                                    <div class="card-body pt-0">
                                        <div class="row">
                                            <div class="col-7">
                                                <h2 class="lead"><b>@x.PersonelAd @x.PersonelSoyad</b></h2>
                                                <p class="text-muted text-sm"><b>About: </b> Web Designer / UX / Graphic Artist / Coffee Lover </p>
                                                <ul class="ml-4 mb-0 fa-ul text-muted">
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                                </ul>
                                            </div>
                                            <div class="col-5 text-center">
                                                <img src="@x.PersonelGorsel" alt="" class="img-circle img-fluid">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <div class="text-right">
                                            <a href="/Personel/PersonelGetir/@x.PersonelID" class="btn btn-sm bg-teal">
                                                <i class="fas fa-comments"></i>
                                            </a>
                                            <a href="/Departman/DepartmanPersonelSatis/@x.PersonelID" class="btn btn-sm btn-primary">
                                                <i class="fas fa-user"></i> Satış Geçmişi
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <!-- /.card-body -->
                <!-- /.card-footer -->
            </div>
            <!-- /.card -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../dist/js/demo.js"></script>
</body>
</html>


\AdminLTE-3.0.4\dist\img\user1-128x128.jpg